### ISSUE TITLE
TypeError: 'UnboundVariable' object does not support indexing

### ISSUE THREAD

**Issue by Patrickcxt** [ikostrikov/TensorFlow-VAE-GAN-DRAW#14]
Hi, when I run the command 'python main-draw.py --working_directory /tmp/gan', I got the following error:

Traceback (most recent call last):
  File "main-draw.py", line 190, in <module>
    gru_cell(num_units=FLAGS.rnn_size, state=pt.UnboundVariable('state')))
  File "/home/amax/anaconda2/lib/python2.7/site-packages/prettytensor/pretty_tensor_class.py", line 2011, in method
    return func(input_layer, *args, **self.fill_kwargs(input_layer, kwargs))
  File "/home/amax/anaconda2/lib/python2.7/site-packages/prettytensor/recurrent_networks.py", line 286, in gru_cell
    state = state[0]
TypeError: 'UnboundVariable' object does not support indexing
The version of my tensorflow is 1.0
I use "pip install prettytensor" to install prettytensor 0.7.4
when I tried the example from the tutorial : https://github.com/google/prettytensor, it failed too
A = (pretty_tensor.template('x')
     .lstm_cell(num_units=256, state=UnboundVariable('state'))

Thanks !

**Comment by ikostrikov** [comment]
The implementation of DRAW is not maintained at the moment. I will fix it as soon as I have time (it might happen in several months).
