### ISSUE TITLE
AttributeError: 'module' object has no attribute '_VariableScope'

### ISSUE THREAD

**Issue by andyyuan78** [ikostrikov/TensorFlow-VAE-GAN-DRAW#5]
envy@ub1404:~/os_pri/github/TensorFlow-VAE-GAN-DRAW$ python main-vae.py --working_directory .
Extracting ./MNIST/train-images-idx3-ubyte.gz
Extracting ./MNIST/train-labels-idx1-ubyte.gz
Extracting ./MNIST/t10k-images-idx3-ubyte.gz
Extracting ./MNIST/t10k-labels-idx1-ubyte.gz
Traceback (most recent call last):
  File "main-vae.py", line 120, in <module>
    output_tensor, mean, stddev = decoder(encoder(input_tensor))
  File "main-vae.py", line 41, in encoder
    reshape([FLAGS.batch_size, 28, 28, 1]).
  File "/home/envy/.local/lib/python2.7/site-packages/prettytensor/pretty_tensor_class.py", line 1816, in method
    with _method_scope(input_layer, scope_name) as (scope, _):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/envy/.local/lib/python2.7/site-packages/prettytensor/pretty_tensor_class.py", line 1628, in _method_scope
    scopes.var_and_name_scope((name, None)) as (scope, var_scope):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/envy/.local/lib/python2.7/site-packages/prettytensor/scopes.py", line 57, in var_and_name_scope
    vs_key[0] = variable_scope._VariableScope(
AttributeError: 'module' object has no attribute '_VariableScope'
envy@ub1404:~/os_pri/github/TensorFlow-VAE-GAN-DRAW$

**Comment by ikostrikov** [comment]
Hi! This error was caused by the latest version of TensorFlow.

You can fix it by editing your local installation of PrettyTensor.

Just replace 
vs_key[0] = variable_scope._VariableScope(
with
vs_key[0] = variable_scope.VariableScope(
in
File "/home/envy/.local/lib/python2.7/site-packages/prettytensor/scopes.py", line 57

**Comment by ikostrikov** [comment]
The bug has been fixed. Please install the latest version of PrettyTensor.
